version: '3'
services:

  #Build y servicio sobre Ubuntu
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: thebluemax/heros
    container_name: app_heros
    restart: unless-stopped
    tty: true
    working_dir: /home/app
    ports:
      - "8088:80"
      - "3000:3000"
